# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

language: generic

  
jobs:
  include:
    - name: macOS / Swift 5.3 (Xcode 12.2)
      os: osx
      language: swift
      osx_image: xcode12.2
      script:
        - swift test
      addons:
        homebrew:
          update: true
          packages: 
            - libressl
          update: true
          taps: vapor/tap
          casks: 
            - vapor

    - &linux
      name: Linux / Swift 5.3
      env: SWIFT_VERSION=5.3.3
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test
